title: "Yoshi Podcasts"
description: "Catalog of podcast episodes recorded with Yoshi Nov & Dec 2024 into Jan 2025"
baseurl: "/yoshi-podcasts"
url: "https://harryf.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-algolia

algolia:
  application_id: DYFWUPT5NY
  index_name: yoshi_podcasts
  search_only_api_key: 9241c9fe7a3d5de5b10cc4bc38891fcc
  url: "https://harryf.github.io/yoshi-podcasts"

# Collections
collections:
  episodes:
    output: true
    permalink: /episodes/:title/
  transcripts:
    output: true
  edits:
    output: true
    permalink: /edits/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - private
  - ignored
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor
  - .git/
  - whisper.cpp
  - youtube
