title: "Yoshi Podcasts"
description: "Catalog of podcast episodes recorded with Yoshi Nov & Dec 2024 into Jan 2025"
baseurl: "/yoshi-podcasts"
url: "https://harryf.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Collections
collections:
  episodes:
    output: true
    permalink: /episodes/:title/

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - private
  - ignored
  - .sass-cache/
  - .jekyll-cache/
  - node_modules/
  - vendor
  - .git/
